version: "3.6"
services:
    database-server:
        env_file:
            - build/sql.env
        image: "benediktschmidt.at/database-server"
        volumes:
            - sqldata:/var/opt/mssql/data
        networks:
            - internal
        ports:
            - "1433:1433"
    homepage:
        image: "benediktschmidt.at/me"
        networks:
            - dmz
    valheim:
        env_file:
            - build/valheim.env
        image: "benediktschmidt.at/valheim"
        volumes:
            - valheimdata:/srv/valheim
        networks:
            - dmz
    corona-viewer:
        environment:
            - DBHOST=database-server
        env_file:
            - build/corona.env
        image: "benediktschmidt.at/corona-viewer"
        networks:
            - dmz
            - internal
    corona-updater:
        env_file:
            - build/corona.env
        image: "benediktschmidt.at/corona-updater"
        volumes:
            - coronadata:/tmp/corona
        networks:
            - internal
    reverse-proxy:
        environment:
            - WEBFQDN=reverse-proxy
            - TARGETCORONA=corona-viewer:80
            - TARGETME=homepage:80
            - TARGETDOWNLOADS=downloads:80
        env_file:
            - environments/reverse-proxy.env
        image: "benediktschmidt.at/reverse-proxy"
        networks:
            dmz:
                aliases:
                    - me.reverse-proxy
                    - corona.reverse-proxy
                    - downloads.reverse-proxy
        ports:
            - "80:80"
    downloads:
        image: "benediktschmidt.at/downloads"
        volumes:
            - downloadsdata:/srv/downloads
        networks:
            - dmz
volumes:
    sqldata:
        external: true
    coronadata:
        external: true
    valheimdata:
        external: true
    downloadsdata:
        external: true
networks:
    internal:
    dmz:
