version: "3.6"
services:
    database-server:
        env_file:
            - /opt/tester/sql.env
        image: "benediktschmidt.at/database-server"
        volumes:
            - sqldata:/var/opt/mssql/data
        networks:
            - internal
        ports:
            - "1433:1433"
    homepage:
        image: "benediktschmidt.at/me"
        networks:
            - internal
        ports:
            - "80:80"
    valheim:
        env_file:
            - /opt/tester/valheim.env
        image: "benediktschmidt.at/valheim"
        networks:
            - internal
    corona:
        image: "benediktschmidt.at/corona"
        networks:
            - internal
volumes:
    sqldata:
        external: true
networks:
    internal:
    dmz:
