version: "3.6"
services:
    database-server:
        env_file:
            - build/sql.env
        image: "benediktschmidt.at/database-server"
        volumes:
            - sqldata:/var/opt/mssql/data
        networks:
            - internal
        ports:
            - "1433:1433"
    homepage:
        image: "benediktschmidt.at/me"
        networks:
            - internal
        ports:
            - "80:80"
    valheim:
        env_file:
            - build/valheim.env
        image: "benediktschmidt.at/valheim"
        volumes:
            - valheimdata:/srv/valheim
        networks:
            - internal
    corona-viewer:
        environment:
            - DBHOST=database-server
        env_file:
            - build/corona.env
        image: "benediktschmidt.at/corona-viewer"
        networks:
            - internal
        ports:
            - "8080:80"
    corona-updater:
        environment:
            - DBHOST=database-server
        env_file:
            - build/corona.env
        image: "benediktschmidt.at/corona-updater"
        volumes:
            - coronadata:/tmp/corona
        networks:
            - internal
volumes:
    sqldata:
        external: true
    coronadata:
        external: true
    valheimdata:
        external: true
networks:
    internal:
    dmz:
