version: "3.6"
services:
    database-server:
        environment:
            - SA_PASSWORD=$BENEDIKTSCHMIDT_AT_SQL_SA_PASSWORD
        image: "benediktschmidt.at/database-server"
    homepage:
        image: "benediktschmidt.at/me"
    valheim:
        environment:
            - VALHEIM_SERVER_NAME=$BENEDIKTSCHMIDT_AT_VALHEIM_SERVER_NAME
            - VALHEIM_SERVER_PASSWORD=$BENEDIKTSCHMIDT_AT_VALHEIM_SERVER_PASSWORD
        image: "benediktschmidt.at/valheim"
