version: "3.6"
services:
    database-server:
        env_file:
            - /opt/tester/sql.env
        image: "benediktschmidt.at/database-server"
        volumes:
            - sqldata:/var/opt/mssql/data
    homepage:
        image: "benediktschmidt.at/me"
    valheim:
        env_file:
            - /opt/tester/valheim.env
        image: "benediktschmidt.at/valheim"
    corona:
        image: "benediktschmidt.at/corona"
volumes:
    sqldata:
        external: true
