version: "3.6"
services:
    vpn:
        env_file:
            - /etc/infrastructure/environments/vpn.env
            - /etc/infrastructure/environments/host.env
        image: "benediktibk/vpn"
        volumes:
            - vpncertificates:/etc/openvpn/certs
        network_mode: host
        privileged: true
        restart: unless-stopped
    firewall:
        env_file:
            - /etc/infrastructure/environments/firewall.env
            - /etc/infrastructure/environments/host.env
        image: "benediktibk/firewall"
        network_mode: host
        privileged: true
        restart: unless-stopped
    util-dmz:
        image: "benediktibk/network-util"
        networks:
            dmz:
                ipv4_address: 192.168.38.254
        restart: unless-stopped
    util-internal:
        image: "benediktibk/network-util"
        networks:
            internal:
                ipv4_address: 192.168.39.254
        restart: unless-stopped
volumes:
    vpncertificates:
        external: true
networks:
    internal:
        name: internal
        ipam:
            config:
                - subnet: 192.168.39.0/24
    dmz:
        name: dmz
        ipam:
            config:
                - subnet: 192.168.38.0/24