version: "3.6"
services:
    database-server:
        env_file:
            - /etc/infrastructure/environments/sql.env
        image: "benediktibk/database-server"
        volumes:
            - sql:/var/opt/mssql/data
    corona-init:
        environment:
            - DBHOST=database-server
        env_file:
            - /etc/infrastructure/environments/corona.env
            - /etc/infrastructure/environments/sql.env
        image: "benediktibk/corona-init"
        volumes:
            - corona:/tmp/corona
volumes:
    sql:
        external: true
    corona:
        external: true
