version: "3.6"
services:
    database-server:
        env_file:
            - /etc/infrastructure/environments/sql.env
        image: "benediktibk/database-server"
        volumes:
            - sql:/var/opt/mssql/data/
        networks:
            internal:
                ipv4_address: 192.168.39.2
    homepage:
        image: "benediktibk/homepage"
        networks:
            dmz:
                ipv4_address: 192.168.38.2
    valheim:
        env_file:
            - /etc/infrastructure/environments/valheim.env
        image: "benediktibk/valheim"
        volumes:
            - valheim:/srv/valheim/
        networks:
            dmz:
                ipv4_address: 192.168.38.3
    corona-viewer:
        environment:
            - DBHOST=192.168.39.2
        env_file:
            - /etc/infrastructure/environments/corona.env
        image: "benediktibk/corona-viewer"
        networks:
            dmz:
                ipv4_address: 192.168.38.4
    corona-updater:
        env_file:
            - /etc/infrastructure/environments/corona.env
        image: "benediktibk/corona-updater"
        volumes:
            - corona:/tmp/corona/
        networks:
            internal:
                ipv4_address: 192.168.39.4
    reverse-proxy:
        environment:
            - WEBFQDN=benediktschmidt.at
            - TARGETCORONA=corona-viewer:80
            - TARGETME=homepage:80
            - TARGETDOWNLOADS=downloads:80
        env_file:
            - /etc/infrastructure/environments/reverse-proxy.env
        image: "benediktibk/reverse-proxy"
        volumes:
            - webcertificates:/etc/nginx/certs/
            - acme:/var/www/html/
        networks:
            dmz:
                ipv4_address: 192.168.38.5
                aliases:
                    - me.reverse-proxy
                    - corona.reverse-proxy
                    - downloads.reverse-proxy
        ports:
            - "80:80"
            - "443:443"
    downloads:
        image: "benediktibk/downloads"
        volumes:
            - downloads:/srv/downloads/
        networks:
            dmz:
                ipv4_address: 192.168.38.6
        env_file:
            - /etc/infrastructure/environments/sql.env
    dc:
        env_file:
            - /etc/infrastructure/environments/dc.env
        image: "benediktibk/dc"
        volumes:
            - dc:/var/lib/samba/
            - /etc/localtime:/etc/localtime:ro
        networks:
            internal:
                ipv4_address: 192.168.39.3
    certbot:
        image: "benediktibk/certbot"
        volumes:
            - webcertificates:/etc/nginx/certs/
            - acme:/var/www/html/
            - letsencrypt:/etc/letsencrypt/live/
        networks:
            internal:
                ipv4_address: 192.168.39.5
volumes:
    sql:
        external: true
    corona:
        external: true
    valheim:
        external: true
    downloads:
        external: true
    webcertificates:
        external: true
    dc:
        external: true
    acme:
        external: true
    letsencrypt:
        external: true
networks:
    internal:
        external: true
    dmz:
        external: true
