version: "3.6"
services:
    database-server:
        env_file:
            - /etc/infrastructure/sql.env
        image: "benediktibk/database-server"
        volumes:
            - sqldata:/var/opt/mssql/data
        networks:
            - internal
    corona-init:
        environment:
            - DBHOST=database-server
        env_file:
            - /etc/infrastructure/corona.env
            - /etc/infrastructure/sql.env
        image: "benediktibk/corona-init"
        volumes:
            - coronadata:/tmp/corona
        networks:
            - internal
volumes:
    sqldata:
        external: true
    coronadata:
        external: true
networks:
    internal:
