version: "3.6"
services:
    database-server:
        env_file:
            - /etc/infrastructure/environments/sql.env
        image: "benediktibk/database-server"
        volumes:
            - sql:/var/opt/mssql/data
        networks:
            - internal
        ports:
            - "1433:1433"
    homepage:
        image: "benediktibk/homepage"
        networks:
            - dmz
    valheim:
        env_file:
            - /etc/infrastructure/environments/valheim.env
        image: "benediktibk/valheim"
        volumes:
            - valheim:/srv/valheim
        networks:
            - dmz
    corona-viewer:
        environment:
            - DBHOST=database-server
        env_file:
            - /etc/infrastructure/environments/corona.env
        image: "benediktibk/corona-viewer"
        networks:
            - dmz
            - internal
    corona-updater:
        env_file:
            - /etc/infrastructure/environments/corona.env
        image: "benediktibk/corona-updater"
        volumes:
            - corona:/tmp/corona
        networks:
            - internal
    reverse-proxy:
        environment:
            - WEBFQDN=dev.benediktschmidt.at
            - TARGETCORONA=corona-viewer:80
            - TARGETME=homepage:80
            - TARGETDOWNLOADS=downloads:80
        env_file:
            - /etc/infrastructure/environments/reverse-proxy.env
        image: "benediktibk/reverse-proxy"
        volumes:
            - webcertificates:/etc/nginx/certs/
        networks:
            dmz:
                aliases:
                    - me.reverse-proxy
                    - corona.reverse-proxy
                    - downloads.reverse-proxy
        ports:
            - "80:80"
            - "443:443"
    downloads:
        image: "benediktibk/downloads"
        volumes:
            - downloads:/srv/downloads
        networks:
            - dmz
volumes:
    sqldata:
        external: true
    coronadata:
        external: true
    valheimdata:
        external: true
    downloadsdata:
        external: true
    webcertificatesdata:
        external: true
networks:
    internal:
        external: true
    dmz:
        external: true
