version: "3.6"
services:
    database-server:
        env_file:
            - /etc/infrastructure/environments/sql.env
        image: "benediktibk/database-server"
        volumes:
            - sql:/var/opt/mssql/data/
        networks:
            internal:
                ipv4_address: 192.168.39.2
    homepage:
        image: "benediktibk/homepage"
        networks:
            dmz:
                ipv4_address: 192.168.38.2
    valheim:
        env_file:
            - /etc/infrastructure/environments/valheim.env
        image: "benediktibk/valheim"
        volumes:
            - valheim:/srv/valheim/
        networks:
            dmz:
                ipv4_address: 192.168.38.3
        ports:
            - "2456:2456/tcp"
            - "2456:2456/udp"
            - "2457:2457/tcp"
            - "2457:2457/udp"
            - "2458:2458/tcp"
            - "2458:2458/udp"
    corona-viewer:
        environment:
            - DBHOST=192.168.39.2
        env_file:
            - /etc/infrastructure/environments/corona.env
        image: "benediktibk/corona-viewer"
        networks:
            dmz:
                ipv4_address: 192.168.38.4
    corona-updater:
        environment:
            - DBHOST=192.168.39.2
        env_file:
            - /etc/infrastructure/environments/corona.env
        image: "benediktibk/corona-updater"
        volumes:
            - corona:/tmp/corona/
        networks:
            internal:
                ipv4_address: 192.168.39.4
    reverse-proxy:
        environment:
            - WEBFQDN=benediktschmidt.at
            - TARGETCORONA=192.168.38.4:80
            - TARGETME=192.168.38.2:80
            - TARGETDOWNLOADS=192.168.38.6:80
            - TARGETMONITORING=192.168.38.8:8080
        env_file:
            - /etc/infrastructure/environments/reverse-proxy.env
        image: "benediktibk/reverse-proxy"
        volumes:
            - webcertificates:/etc/nginx/certs/
            - acme:/var/www/html/
            - proxycache:/data/nginx/cache/
        networks:
            dmz:
                ipv4_address: 192.168.38.5
                aliases:
                    - me.reverse-proxy
                    - corona.reverse-proxy
                    - downloads.reverse-proxy
        ports:
            - "80:80"
            - "443:443"
    downloads:
        image: "benediktibk/downloads"
        volumes:
            - downloads:/srv/downloads/
        networks:
            dmz:
                ipv4_address: 192.168.38.6
        env_file:
            - /etc/infrastructure/environments/sql.env
    dc:
        image: "benediktibk/dc"
        volumes:
            - dc:/var/lib/samba/
            - /etc/localtime:/etc/localtime:ro
        networks:
            internal:
                ipv4_address: 192.168.39.3
        cap_add:
            - SYS_ADMIN
        hostname: DC1
    certbot:
        image: "benediktibk/certbot"
        volumes:
            - webcertificates:/etc/nginx/certs/
            - acme:/var/www/html/
            - letsencrypt:/etc/letsencrypt/
        networks:
            internal:
                ipv4_address: 192.168.39.5
    amongus:
        image: "benediktibk/amongus"
        networks:
            dmz:
                ipv4_address: 192.168.38.7
        ports:
            - "22023:22023/udp"
    postgres:
        env_file:
            - /etc/infrastructure/environments/postgres.env
        image: "benediktibk/postgres"
        volumes:
            - postgres:/var/lib/postgresql/data/
        networks:
            internal:
                ipv4_address: 192.168.39.6
    zabbix-server:
        environment:
            - DB_SERVER_HOST=192.168.39.6
        env_file:
            - /etc/infrastructure/environments/zabbix-server.env
        image: "benediktibk/zabbix-server"
        networks:
            internal:
                ipv4_address: 192.168.39.7
    zabbix-frontend:
        environment:
            - ZBX_SERVER_HOST=192.168.39.7
            - DB_SERVER_HOST=192.168.39.6
        env_file:
            - /etc/infrastructure/environments/zabbix-frontend.env
        image: "benediktibk/zabbix-frontend"
        networks:
            dmz:
                ipv4_address: 192.168.38.8
    downloads-share:
        image: "benediktibk/downloads-share"
        volumes:
            - downloads:/srv/downloads
        networks:
            internal:
                ipv4_address: 192.168.39.8
    cron-passwords:
        env_file:
            - /etc/infrastructure/environments/cron-passwords.env
        image: "benediktibk/cron-passwords"
        networks:
            internal:
                ipv4_address: 192.168.39.9
    cron-volume-backup:
        env_file:
            - /etc/infrastructure/environments/cron-volume-backup.env
        image: "benediktibk/cron-volume-backup"
        volumes:
            - acme:/mnt/volumes/acme
            - corona:/mnt/volumes/corona
            - dc:/mnt/volumes/dc
            - downloads:/mnt/volumes/downloads
            - letsencrypt:/mnt/volumes/letsencrypt
            - postgres:/mnt/volumes/postgres
            - proxycache:/mnt/volumes/proxycache
            - sql:/mnt/volumes/sql
            - valheim:/mnt/volumes/valheim
            - vpncertificates:/mnt/volumes/vpncertificates
            - webcertificates:/mnt/volumes/webcertificates
        privileged: true
        networks:
            internal:
                ipv4_address: 192.168.39.10
    cron-storage-backup:
        env_file:
            - /etc/infrastructure/environments/cron-storage-backup.env
        image: "benediktibk/cron-volume-backup"
        volumes:
            - storagebackup:/mnt/storagebackup
        privileged: true
        networks:
            internal:
                ipv4_address: 192.168.39.11

volumes:
    sql:
        external: true
    corona:
        external: true
    valheim:
        external: true
    downloads:
        external: true
    webcertificates:
        external: true
    vpncertificates:
        external: true
    dc:
        external: true
    acme:
        external: true
    letsencrypt:
        external: true
    proxycache:
        external: true
    postgres:
        external: true
    storagebackup:
        external: true
networks:
    internal:
        external: true
    dmz:
        external: true
