- name: reload daemons
  shell: "systemctl daemon-reload"
- name: enable infrastructure service
  shell: "systemctl enable infrastructure"
#- name: enable firewall
#  shell: "systemctl enable nftables"
- name: start infrastructure service
  shell: "systemctl start infrastructure"
#- name: restart firewall
#  shell: "systemctl restart nftables"