- name: copy sql environment
  become: true
  copy:
    src: /etc/infrastructure/environments/sql.env
    dest: /etc/infrastructure/environments/sql.env
- name: copy corona environment
  become: true
  copy:
    src: /etc/infrastructure/environments/corona.env
    dest: /etc/infrastructure/environments/corona.env
- name: copy reverse-proxy environment
  become: true
  copy:
    src: /etc/infrastructure/environments/reverse-proxy.env
    dest: /etc/infrastructure/environments/reverse-proxy.env
- name: copy valheim environment
  become: true
  copy:
    src: /etc/infrastructure/environments/valheim.env
    dest: /etc/infrastructure/environments/valheim.env
- name: copy vpn environment
  become: true
  copy:
    src: /etc/infrastructure/environments/vpn.env
    dest: /etc/infrastructure/environments/vpn.env
- name: copy firewall environment
  become: true
  copy:
    src: /etc/infrastructure/environments/firewall.env
    dest: /etc/infrastructure/environments/firewall.env
- name: copy infrastructure-network service definition
  become: true
  copy:
    src: ../service-definitions/infrastructure-network.service
    dest: /etc/systemd/system/infrastructure-network.service
- name: copy infrastructure-services service definition
  become: true
  copy:
    src: ../service-definitions/infrastructure-services.service
    dest: /etc/systemd/system/infrastructure-services.service
- name: copy docker compose file
  become: true
  copy:
    src: ../compose-files/services.yaml
    dest: /etc/infrastructure/services.yaml
- name: copy docker compose file
  become: true
  copy:
    src: ../compose-files/services-init.yaml
    dest: /etc/infrastructure/services-init.yaml
- name: copy docker compose file
  become: true
  copy:
    src: ../compose-files/network.yaml
    dest: /etc/infrastructure/network.yaml
- name: copy root CA certificate
  become: true
  copy:
    src: ../build/secrets/ca/root_ca.crt
    dest: /usr/local/share/ca-certificates/
- name: update root CA certificates
  shell: "update-ca-certificates"
- name: copy VPN certificate
  become: true
  copy:
    src: ../build/secrets/ca/root_ca.crt
    dest: /var/lib/docker/volumes/vpncertificates/_data/ca.crt
- name: copy VPN certificate
  become: true
  copy:
    src: ../build/secrets/ca/vpn_server.crt
    dest: /var/lib/docker/volumes/vpncertificates/_data/server.crt
- name: copy VPN certificate
  become: true
  copy:
    src: ../build/secrets/ca/vpn_server.key
    dest: /var/lib/docker/volumes/vpncertificates/_data/server.key
- name: copy VPN certificate
  become: true
  copy:
    src: ../build/secrets/ca/dh-vpn.pem
    dest: /var/lib/docker/volumes/vpncertificates/_data/dh.pem
- name: copy syslog config
  become: true
  copy:
    src: ../configs/syslog-nftables.conf
    dest: /etc/rsyslog.d/nftables.conf
- name: copy logrotate config
  become: true
  copy:
    src: ../configs/logrotate-nftables
    dest: /etc/logrotate.d/nftables