- name: pull images of infrastructure-services
  shell: "/usr/bin/docker-compose --project-name infrastructure-services -f /etc/infrastructure/services.yaml pull"
- name: update containers of infrastructure-services
  shell: "/usr/bin/docker-compose --project-name infrastructure-services -f /etc/infrastructure/services.yaml up -d --remove-orphans"