- name: copy sql environment
  become: true
  copy:
    src: ../build/environments/sql.env
    dest: /etc/infrastructure/environments/sql.env
- name: copy corona environment
  become: true
  copy:
    src: ../build/environments/corona.env
    dest: /etc/infrastructure/environments/corona.env
- name: copy reverse-proxy environment
  become: true
  copy:
    src: ../build/environments/reverse-proxy.env
    dest: /etc/infrastructure/environments/reverse-proxy.env
- name: copy valheim environment
  become: true
  copy:
    src: ../build/environments/valheim.env
    dest: /etc/infrastructure/environments/valheim.env
- name: copy postgres environment
  become: true
  copy:
    src: ../build/environments/postgres.env
    dest: /etc/infrastructure/environments/postgres.env
- name: copy zabbix-server environment
  become: true
  copy:
    src: ../build/environments/zabbix-server.env
    dest: /etc/infrastructure/environments/zabbix-server.env
- name: copy zabbix-frontend environment
  become: true
  copy:
    src: ../build/environments/zabbix-frontend.env
    dest: /etc/infrastructure/environments/zabbix-frontend.env
- name: copy cron-passwords environment
  become: true
  copy:
    src: ../build/environments/cron-passwords.env
    dest: /etc/infrastructure/environments/cron-passwords.env
- name: copy cron-volume-backup environment
  become: true
  copy:
    src: ../build/environments/cron-volume-backup.env
    dest: /etc/infrastructure/environments/cron-volume-backup.env
- name: copy cron-storage-backup environment
  become: true
  copy:
    src: ../build/environments/cron-storage-backup.env
    dest: /etc/infrastructure/environments/cron-storage-backup.env
- name: copy google-drive-triest environment
  become: true
  copy:
    src: ../build/environments/google-drive-triest.env
    dest: /etc/infrastructure/environments/google-drive-triest.env
- name: copy cron-triest-backup environment
  become: true
  copy:
    src: ../build/environments/cron-triest-backup.env
    dest: /etc/infrastructure/environments/cron-triest-backup.env
- name: copy vpn environment
  become: true
  copy:
    src: ../build/environments/vpn.env
    dest: /etc/infrastructure/environments/vpn.env
- name: copy firewall environment
  become: true
  copy:
    src: ../build/environments/firewall.env
    dest: /etc/infrastructure/environments/firewall.env
- name: copy infrastructure-network service definition
  become: true
  copy:
    src: ../service-definitions/infrastructure-network.service
    dest: /etc/systemd/system/infrastructure-network.service
- name: copy infrastructure-services service definition
  become: true
  copy:
    src: ../service-definitions/infrastructure-services.service
    dest: /etc/systemd/system/infrastructure-services.service
- name: copy docker compose file
  become: true
  copy:
    src: ../compose-files/services.yaml
    dest: /etc/infrastructure/services.yaml
- name: copy docker compose file
  become: true
  copy:
    src: ../compose-files/corona-init.yaml
    dest: /etc/infrastructure/corona-init.yaml
- name: copy docker compose file
  become: true
  copy:
    src: ../compose-files/network.yaml
    dest: /etc/infrastructure/network.yaml
- name: copy root CA certificate
  become: true
  copy:
    src: ../build/secrets/ca/root_ca.crt
    dest: /usr/local/share/ca-certificates/
- name: update root CA certificates
  shell: "update-ca-certificates"
- name: copy VPN certificate
  become: true
  copy:
    src: ../build/secrets/ca/root_ca.crt
    dest: /var/lib/docker/volumes/vpncertificates/_data/ca.crt
- name: copy VPN certificate
  become: true
  copy:
    src: ../build/secrets/ca/vpn_server.crt
    dest: /var/lib/docker/volumes/vpncertificates/_data/server.crt
- name: copy VPN certificate
  become: true
  copy:
    src: ../build/secrets/ca/vpn_server.key
    dest: /var/lib/docker/volumes/vpncertificates/_data/server.key
- name: copy VPN certificate
  become: true
  copy:
    src: ../build/secrets/ca/dh-vpn.pem
    dest: /var/lib/docker/volumes/vpncertificates/_data/dh.pem
- name: copy LDAP certificate
  become: true
  copy:
    src: ../build/secrets/ca/ldap_dc1.benediktschmidt.at.crt
    dest: /var/lib/docker/volumes/ldapcertificates/_data/ldap_dc1.benediktschmidt.at.crt
- name: copy LDAP certificate
  become: true
  copy:
    src: ../build/secrets/ca/ldap_dc1.benediktschmidt.at.key
    dest: /var/lib/docker/volumes/ldapcertificates/_data/ldap_dc1.benediktschmidt.at.key
- name: set file permissions of LDAP certificate
  shell: "chmod 600 /var/lib/docker/volumes/ldapcertificates/_data/ldap_dc1.benediktschmidt.at.key"
- name: copy syslog config
  become: true
  copy:
    src: ../configs/syslog-nftables.conf
    dest: /etc/rsyslog.d/nftables.conf
- name: copy logrotate config
  become: true
  copy:
    src: ../configs/logrotate-nftables
    dest: /etc/logrotate.d/nftables
- name: copy google drive triest credentials
  become: true
  copy:
    src: ../build/secrets/passwords/google-drive-triest-credentials.json
    dest: /etc/infrastructure/google-drive-triest-credentials.json