- name: reload daemons
  shell: "systemctl daemon-reload"
- name: enable infrastructure-services
  shell: "systemctl enable infrastructure-services"
- name: enable infrastructure-network
  shell: "systemctl enable infrastructure-network"
- name: restart syslog
  shell: "systemctl restart rsyslog"
- name: start infrastructure-services
  shell: "systemctl start infrastructure-services"
- name: start infrastructure-network
  shell: "systemctl start infrastructure-network"