FROM debian:stable
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y wget
RUN apt-get install -y iputils-ping
RUN ln -s /usr/bin/fping /usr/sbin/fping
RUN ln -s /usr/bin/fping6 /usr/sbin/fping6
RUN wget https://repo.zabbix.com/zabbix/7.4/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.4+debian13_all.deb
RUN dpkg -i zabbix-release_latest_7.4+debian13_all.deb
RUN apt-get update
RUN apt-get install -y zabbix-server-pgsql
RUN apt-get install -y zabbix-get
COPY zabbix_server.conf.template /zabbix_server.conf.template
COPY start.sh /start.sh
CMD ["/start.sh"]