FROM debian:stable
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get -y install openvpn
RUN apt-get -y install gettext-base
COPY server.conf.template /etc/openvpn/server/
RUN mkdir -p /etc/openvpn/server/clients
RUN mkdir -p /etc/openvpn/certs
RUN adduser --system --no-create-home --shell /dev/null --group --disabled-login openvpn
COPY *.location.benediktschmidt.at /etc/openvpn/server/clients/
COPY openvpn-start.sh /
CMD ["/openvpn-start.sh"]