FROM debian:stable
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt-get -y install nftables
COPY firewall.sh /
RUN chmod 700 /firewall.sh
COPY blacklist_ipadb.txt /
COPY blacklist_firehol.txt /
CMD ["/firewall.sh"]