FROM nginx
COPY default.conf.template /etc/nginx/conf.d/
COPY nginx.conf /etc/nginx/
COPY nginx-start.sh /
RUN mkdir -p /etc/nginx/certs
RUN mkdir -p /etc/nginx/certs-temp
COPY root_ca.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates
RUN openssl req -x509 -newkey rsa:4096 -keyout /etc/nginx/certs-temp/web_benediktschmidt.at.key -out /etc/nginx/certs-temp/web_benediktschmidt.at.crt -sha256 -days 365 -nodes -subj '/CN=localhost'
RUN cp /etc/nginx/certs-temp/web_benediktschmidt.at.key /etc/nginx/certs-temp/web_www.benediktschmidt.at.key
RUN cp /etc/nginx/certs-temp/web_benediktschmidt.at.key /etc/nginx/certs-temp/web_me.benediktschmidt.at.key
RUN cp /etc/nginx/certs-temp/web_benediktschmidt.at.key /etc/nginx/certs-temp/web_downloads.benediktschmidt.at.key
RUN cp /etc/nginx/certs-temp/web_benediktschmidt.at.key /etc/nginx/certs-temp/web_monitoring.benediktschmidt.at.key
RUN cp /etc/nginx/certs-temp/web_benediktschmidt.at.key /etc/nginx/certs-temp/web_cloud.benediktschmidt.at.key
RUN cp /etc/nginx/certs-temp/web_benediktschmidt.at.key /etc/nginx/certs-temp/web_apt.benediktschmidt.at.key
RUN cp /etc/nginx/certs-temp/web_benediktschmidt.at.crt /etc/nginx/certs-temp/web_www.benediktschmidt.at.crt
RUN cp /etc/nginx/certs-temp/web_benediktschmidt.at.crt /etc/nginx/certs-temp/web_me.benediktschmidt.at.crt
RUN cp /etc/nginx/certs-temp/web_benediktschmidt.at.crt /etc/nginx/certs-temp/web_downloads.benediktschmidt.at.crt
RUN cp /etc/nginx/certs-temp/web_benediktschmidt.at.crt /etc/nginx/certs-temp/web_monitoring.benediktschmidt.at.crt
RUN cp /etc/nginx/certs-temp/web_benediktschmidt.at.crt /etc/nginx/certs-temp/web_cloud.benediktschmidt.at.crt
RUN cp /etc/nginx/certs-temp/web_benediktschmidt.at.crt /etc/nginx/certs-temp/web_apt.benediktschmidt.at.crt
CMD ["/nginx-start.sh"]