FROM debian:stable
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y smbclient
RUN apt-get install -y cron
COPY cronjobs /etc/crontabs/root
COPY copy-passwords.sh /
RUN chmod 755 /copy-passwords.sh
CMD ["cron", "-f"]