FROM debian:stable
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y nano
RUN apt-get install -y samba
RUN adduser --system --no-create-home --shell /dev/null --group --disabled-login samba-guest
RUN smbpasswd -a -n samba-guest
COPY smb.conf /etc/samba/smb.conf
COPY start.sh /
RUN chmod 755 /start.sh
RUN mkdir /srv/downloads
CMD /start.sh