FROM debian:stable
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y cifs-utils
RUN apt-get install -y cron
RUN mkdir /mnt/googledrivetriest
RUN mkdir /mnt/storage1
RUN mkdir /tmp/backup
COPY cronjobs /etc/cron.d/cronjobs
RUN chmod 0644 /etc/cron.d/cronjobs
RUN crontab /etc/cron.d/cronjobs
COPY backup-triest.sh /
RUN chmod 755 /backup-triest.sh
CMD ["cron", "-f"]