FROM debian:stable
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y nginx
RUN apt-get install -y gettext
RUN apt-get install -y php-fpm
COPY server-28.0.0 /srv/cloud-web
RUN rm -fR /etc/nginx/conf.d/*.conf
RUN rm -fR /etc/nginx/sites-enabled/*
RUN rm -f /etc/php/8.2/fpm/pool.d/www.conf
RUN rm -f /etc/php/8.2/fpm/php-fpm.conf.dpkg-dist
COPY default.conf /etc/nginx/conf.d/
COPY nginx-start.sh /
COPY config.php.template /srv/cloud-web/config/
COPY php.conf /etc/php/8.2/fpm/conf.d/nextcloud.conf
COPY php-fpm.conf /etc/php/8.2/fpm/php-fpm.conf
COPY nextcloud-php-fpm.conf /etc/php/8.2/fpm/pool.d/
RUN mkdir -p /srv/cloud-data
CMD ["/nginx-start.sh"]