FROM debian:stable
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y smbclient
RUN apt-get install -y cron
COPY cronjobs /etc/cron.d/cronjobs
RUN chmod 0644 /etc/cron.d/cronjobs
RUN crontab /etc/cron.d/cronjobs
COPY copy-passwords.sh /
RUN chmod 755 /copy-passwords.sh
COPY fstab /etc/fstab
COPY start.sh /
RUN chmod 755 /start.sh
CMD ["/start.sh"]