FROM debian:stable
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y wget
RUN apt-get install -y locales
RUN wget https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-1+debian11_all.deb
RUN dpkg -i zabbix-release_6.0-1+debian11_all.deb
RUN apt-get update
RUN apt-get install -y zabbix-frontend-php
RUN apt-get install -y php7.4-pgsql
RUN apt-get install -y zabbix-nginx-conf
RUN mkdir -p /var/lib/locales/supported.d/
RUN echo "en_US.UTF-8 UTF-8" > /var/lib/locales/supported.d/local
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
RUN dpkg-reconfigure locales
COPY root_ca.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates
RUN rm -fR /etc/nginx/conf.d/*.conf
RUN rm -fR /etc/nginx/sites-enabled/*
RUN rm -f /etc/php/7.4/fpm/pool.d/www.conf
RUN rm -f /etc/php/7.4/fpm/php-fpm.conf.dpkg-dist
COPY php.conf /etc/php/7.4/fpm/conf.d/zabbix.conf
COPY php-fpm.conf /etc/php/7.4/fpm/php-fpm.conf
COPY zabbix.conf.php.template /zabbix.conf.php.template
COPY nginx.conf /etc/nginx/conf.d/zabbix.conf
RUN mkdir -p /var/run/php/
COPY start.sh /start.sh
CMD ["/start.sh"]
