FROM nginx
COPY default.conf.template /etc/nginx/conf.d/
COPY nginx-start.sh /
RUN mkdir -p /etc/nginx/certs
COPY root_ca.crt //usr/local/share/ca-certificates/
RUN update-ca-certificates
CMD ["/nginx-start.sh"]