FROM debian:stable
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y cron
RUN apt-get install -y sed
RUN apt-get install -y ca-certificates
RUN apt-get install -y rclone
COPY cronjobs /etc/cron.d/cronjobs
RUN chmod 0644 /etc/cron.d/cronjobs
RUN crontab /etc/cron.d/cronjobs
COPY rclone.conf.template /
COPY start.sh /
COPY sync.sh /
RUN chmod 755 /start.sh
RUN chmod 755 /sync.sh
RUN mkdir /mnt/googledrivetriest
CMD /start.sh