FROM ubuntu:22.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y curl
RUN apt-get install -y libatomic1
RUN apt-get install -y curl
RUN apt-get install -y libpulse-dev
RUN apt-get install -y libpulse0
COPY bin/ /opt/valheim/
COPY start_server.sh /opt/valheim/start_server.sh
WORKDIR /opt/valheim/
CMD ["/bin/bash", "start_server.sh"] 