FROM debian:stable
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y wget
RUN wget https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-1+debian11_all.deb
RUN dpkg -i zabbix-release_6.0-1+debian11_all.deb
RUN apt-get update
RUN apt-get install -y zabbix-server-pgsql
COPY zabbix_server.conf.template /zabbix_server.conf.template
COPY start.sh /start.sh
CMD ["/start.sh"]