- name: docker host update
  hosts: docker_hosts
  tasks:
    - include_tasks: tasks/infrastructure-service-files.yaml
    - include_tasks: tasks/infrastructure-service-directories-permissions.yaml
    - include_tasks: tasks/infrastructure-service-container-update-services.yaml