- name: docker host update
  #hosts: docker_hosts_vpn
  hosts: docker_hosts
  tasks:
    - include_tasks: tasks/system-update.yaml
    - include_tasks: tasks/infrastructure-service-stop.yaml
    - include_tasks: tasks/infrastructure-service-files.yaml
    - include_tasks: tasks/infrastructure-service-directories-permissions.yaml
    - include_tasks: tasks/infrastructure-service-start.yaml